# -*- coding: utf-8 -*-
"""Digital Image Processing Lab 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kAOVdDAaw3Pd_AfE1p9Rr-itd4E-bft7
"""

#Read an image and appply the folliwing terms: a)Rersize b)crop c)border
#Read an image dataset and display

import numpy as np
import cv2
from skimage import io
import matplotlib.pyplot as plt
image = io.imread('https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/fiat-500x-cross-884.jpg?itok=fLWsoR6y')
plt.imshow(image)
plt.show()

resized_image = cv2.resize(image, (1000, 800))

# Display the resized image
plt.imshow(resized_image)
plt.show()

x1, y1 = 100, 150
x2, y2 = 400, 350

# Crop the image using NumPy slicing
cropped_image = image[y1:y2, x1:x2]
plt.imshow(cropped_image)
plt.show()

border_width = 10  # You can adjust this value as needed
border_color = (0, 255, 0)  # Border color in BGR format (Green in this example)

# Add the border to the image
bordered_image = cv2.copyMakeBorder(image, border_width, border_width, border_width, border_width, cv2.BORDER_CONSTANT, value=border_color)
plt.imshow(bordered_image)
plt.show()

#Read an image dataset and display

from google.colab import drive
drive.mount('/content/drive')

import cv2
import os
import matplotlib.pyplot as plt


folder_path = '/content/drive/MyDrive/Resources /ML/dataset'

image_files = [f for f in os.listdir(folder_path) if f.endswith(('.jpg', '.jpeg', '.png', '.bmp'))]


for image_file in image_files:

    image_path = os.path.join(folder_path, image_file)


    image = cv2.imread(image_path)

    if image is not None:
        resized_image = cv2.resize(image, (400, 350))
        border_width = 5
        border_color = (255, 100, 0)
        bordered_image = cv2.copyMakeBorder(resized_image, border_width, border_width, border_width, border_width, cv2.BORDER_CONSTANT, value=border_color)
        plt.imshow(cv2.cvtColor(bordered_image, cv2.COLOR_BGR2RGB))
        plt.axis('off')
        plt.show()