# -*- coding: utf-8 -*-
"""Digital Image Processing Lab -2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZqrFYPx8LTO5S5kB5JN5bUwdzv53HcHq
"""

import numpy as np
import cv2
print("OpenCV-Python Version {}".format(cv2.__version__))
from skimage import io
import matplotlib.pyplot as plt
image = io.imread('https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/fiat-500x-cross-884.jpg?itok=fLWsoR6y')
plt.imshow(image)
plt.show()

gray_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
plt.imshow(gray_image, cmap='gray')
plt.show()

mirrored = cv2.flip(image, -1)
plt.imshow(mirrored)
plt.show()

