# -*- coding: utf-8 -*-
"""DIPLAB-Final-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lqREUORqXuueD3HSHaZyNIEccSutoK0p
"""

#Take ann image dataset and apply the following filtering :
1) Laplacian 2)Filtering using Sobel Operator

from google.colab import drive
drive.mount('/content/drive')

import cv2
import os
from google.colab import drive
import matplotlib.pyplot as plt

dataset_path = "/content/drive/MyDrive/Resources /ML/dataset"



for filename in os.listdir(dataset_path):
    if filename.endswith(".jpeg") or filename.endswith(".png"):

        img_path = os.path.join(dataset_path, filename)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)


        laplacian = cv2.Laplacian(img, cv2.CV_64F)


        sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=5)
        sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=5)
        sobel = cv2.magnitude(sobelx, sobely)


        plt.figure(figsize=(12, 6))

        plt.subplot(1, 3, 1)
        plt.imshow(img, cmap='gray')
        plt.title('Original')
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(laplacian, cmap='gray')
        plt.title('Laplacian Filtered')
        plt.axis('off')

        plt.subplot(1, 3, 3)
        plt.imshow(sobel, cmap='gray')
        plt.title('Sobel Filtered')
        plt.axis('off')

        plt.show()